### ISSUE TITLE
Question about initialization of {T_s}

### ISSUE THREAD

**Issue by EmeryLee97** [eriksandstroem/Loopy-SLAM#3]
Hello, in the paper you said the global keyframe pose corrections {T_s} are initialized to identity and so are the constraints {I_s} between the adjacent keyframes. But according to equation (7) in the paper, the alignment error would be 0 and the gradients will also be zero. How did you deal with this vanishing gradient problem? (If you add a small noise to identity matrix will make the odometry alignment error much smaller than loop alignment error, that seems to be a problem in my opinion)

**Comment by eriksandstroem** [comment]
Hi @EmeryLee97,
Very sorry for my late reply. You are correct that the odometry constraints are set to identity, making equation 7 zero, but for the loop edges, equation 7 will not be zero since the constraints are not identity, thus providing the necessary gradient to update the keyframe poses. 

Hope that helps!
